# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

remote_theme: "mmistakes/so-simple-theme@3.2.0"
locale: en-US
title: "Scott Bouloutian"
description: "Developer · Hacker · Engineer"
baseurl: "/"
url: "https://scottbouloutian.com"
logo: "/images/site-logo.png"
skin: "/assets/css/skins/default.css"
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200
mathjax: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: "UA-111142375-1"
disqus:
  shortname: scottbouloutian
twitter:
  username: ScottBouloutian

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Jekyll plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Site Author
author:
  name: Scott Bouloutian
  picture: /images/bio-photo.jpg
  email:
  twitter: ScottBouloutian
  links:
    - title: Twitter
      url: https://twitter.com/ScottBouloutian
      icon: fab fa-twitter-square
    - title: Instagram
      url: https://instagram.com/ScottBouloutian
      icon: fab fa-instagram
    - title: GitHub
      url: https://github.com/ScottBouloutian
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/ScottBouloutian
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/ScottBouloutian
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/ScottBouloutian
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

# Head scripts
head_scripts:
  - /assets/js/adsense.js
